
     HECDSS Complete Catalog of Record Pathnames in File S:\U0029\Work\Models\Buffalo\W100_00_00\E100_100.DSS

     Catalog Created on Feb 4, 2003 at 15:54     File Created on Nov 29, 2001
     Number of Records:      2                   DSS Version 6-MC,  File 6-JG
     Sort Order: ABCFED

  Ref.
 Number   Tag           Record Pathname

     1  T1        //E10019/FLOW/01DEC1982/15MIN//
     2  T2        //E10019/FLOW/01JAN1983/15MIN//
